#### Day 02 : Basics of Matrix Algebra

In [1]:
import numpy as np

# 3 x 2 matrix formation
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [3]:
Q = np.array([[1,1], [1,-1], [2,3]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 2  3]]


In [ ]:
C1 = np.add(P,Q) # adding two matrices of same size
print(C1)

[[2 8]
 [3 0]
 [5 5]]


In [ ]:
C2 = np.subtract(P,Q) # subtracting two matrices of same size
print(C2)

[[ 0  6]
 [ 1  2]
 [ 1 -1]]


In [9]:
R = np.array([[3,2,1],[1,2,5]])
print(R)

[[3 2 1]
 [1 2 5]]


In [11]:
C3 = np.dot(P,R)
print(C3) # matrix multiplication resulting in 3 x 3 matrix formation

[[10 16 36]
 [ 7  6  7]
 [11 10 13]]


#### Finding the determinant of matrix

In [12]:
det = np.linalg.det(C3)
print(det)

-1.3500311979441893e-13


In [15]:
S2 = np.linalg.inv(C3)
print(S2)

[[-5.92578898e+13 -1.12589991e+15  7.70352568e+14]
 [ 1.03701307e+14  1.97032484e+15 -1.34811699e+15]
 [-2.96289449e+13 -5.62949953e+14  3.85176284e+14]]


In [16]:
M=np.array([[1,-1],[2,3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
