### Day 01 : Vectors In Machine Learning

In [1]:
import numpy as np
v=np.array([1,-1,2])
w=np.array([2,5,2])

print(v+w)

[3 4 4]


In [2]:
print(v-w)

[-1 -6  0]


##### Scalar Multiplication With Vector Results a vector

In [3]:
print(3*v)

[ 3 -3  6]


##### Finding Length of a Vector

In [4]:
print(np.linalg.norm(v))

2.449489742783178


#### Dot Product of 2 Vectors

In [5]:
s=np.dot(v,w)
print(s)

1
